# Generated by Django 3.2 on 2024-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('is_repeated_guest', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hotels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_canceled', models.IntegerField(blank=True, null=True)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('arrival_date_year', models.IntegerField(blank=True, null=True)),
                ('arrival_date_month', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_date_week_number', models.IntegerField(blank=True, null=True)),
                ('arrival_date_day_of_month', models.IntegerField(blank=True, null=True)),
                ('stays_in_weekend_nights', models.IntegerField(blank=True, null=True)),
                ('stays_in_week_nights', models.IntegerField(blank=True, null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('babies', models.IntegerField(blank=True, null=True)),
                ('previous_cancellations', models.IntegerField(blank=True, null=True)),
                ('previous_bookings_not_canceled', models.IntegerField(blank=True, null=True)),
                ('reserved_room_type', models.CharField(blank=True, max_length=1, null=True)),
                ('assigned_room_type', models.CharField(blank=True, max_length=1, null=True)),
                ('deposit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('days_in_waiting_list', models.IntegerField(blank=True, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('required_car_parking_spaces', models.IntegerField(blank=True, null=True)),
                ('total_of_special_requests', models.IntegerField(blank=True, null=True)),
                ('reservation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reservation_status_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
    ]
